### ISSUE TITLE
Null safety with intl.

### ISSUE THREAD

**Issue by UjjawalPanchal** [johnpryan/date_utils#19]
I am getting this error,

Because date_utils >=0.1.0+3 depends on intl ^0.16.0 and date_utils >=0.1.0 <=0.1.0+2 depends on intl ^0.15.0, date_utils >=0.1.0 requires intl ^0.15.0 or ^0.16.0.
So, because flutter_cicle_app depends on both date_utils ^0.1.0 and intl ^0.17.0-nullsafety.2, version solving failed.
pub get failed (1; So, because flutter_cicle_app depends on both date_utils ^0.1.0 and intl ^0.17.0-nullsafety.2, version solving failed.)

Can anyone help me with this error?

**Comment by DanMossa** [comment]
I am also having this issue. I believe we have to wait for date_utils to use a different version of intl

**Comment by johnpryan** [comment]
I'm about to release `date_utils 0.2.0`, which upgrades to `intl 0.17.0`. Please reopen if this is still happening, thanks!
